---
kind: Service
apiVersion: v1
metadata:
  name: bosh-external
  labels:
spec:
  ports:
    - name: director
      port: 25555
      targetPort: 25555
      nodePort: 30555
    - name: create-env
      port: 6868
      targetPort: 6868
      nodePort: 30068
  type: NodePort
