---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: loewenstein/ci-gcloud

inputs:
  - name: cpi-src
  - name: prepare-namespace

outputs: []

run:
  path: cpi-src/ci/tasks/delete-namespace.sh
params:
  - SERVICE_ACCOUNT_KEY: ""
  - PROJECT: ""
  - ZONE: ""
  - CLUSTER: ""
