---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: loewenstein/ci-gcloud

inputs:
  - name: cpi-src

outputs:
  - name: prepare-namespace

run:
  path: cpi-src/ci/tasks/prepare-namespace.sh
params:
  - SERVICE_ACCOUNT_KEY: ""
  - PROJECT: ""
  - ZONE: ""
  - CLUSTER: ""
