---
kind: Service
apiVersion: v1
metadata:
  name: bosh-external
spec:
  ports:
    - name: director
      port: 25555
      targetPort: 25555
    - name: create-env
      port: 6868
      targetPort: 6868
    - name: ssh
      port: 22
      targetPort: 22
  type: LoadBalancer
