#!/bin/bash

set -e

if [ "" == "${1:-}" ] ; then
  echo "ERROR: include an image name as the first argument" 2>&1
  exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
IMAGE_NAME="$1"
DOCKER_IMAGE=${DOCKER_IMAGE:-loewenstein/$IMAGE_NAME}


exec docker run --privileged -v $DIR/../..:/opt/bosh-kubernetes-cpi-release --workdir /opt/bosh-kubernetes-cpi-release -t -i $DOCKER_IMAGE
